import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
const poppins = Poppins({ weight: "400", subsets: ["latin"] });
//www.youtube.com/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` no-scrollbar bg-[rgba(250,250,250,1)] ${poppins.className}`}
      >
        <NavBar />
        <div className=" ">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
