import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
const poppins = Poppins({ weight: "300", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavBar />
        <div className="container mx-auto px-4">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
