import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import Provider from "./redux/Provider";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });
//www.youtube.com/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <html lang="en">
        <body className={` bg-[rgba(250,250,250,1)] ${poppins.className}`}>
          <NavBar />
          <div className="">{children}</div> hello layout
          <Footer />
        </body>
      </html>
    </Provider>
  );
}
