import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./../globals.css";
import NavBar from "../components/site/navbar/NavBar";
import Footer from "../components/site/footer/Footer";
import Provider from "../redux/Provider";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });
//www.youtube.com/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  className,
}: Readonly<{
  children: React.ReactNode;
  className?: string;
}>) {
  return (
    <Provider>
      <html lang="en">
        <body className={` bg-[rgba(250,250,250,1)] ${poppins.className}`}>
          <NavBar />
          <div
            // className={`${className} max-w-screen-xl md:mx-auto mx-0 px-4 md:px-14`}
            className={`${className}`}
          >
            {children}
          </div>
          <Footer />
        </body>
      </html>
    </Provider>
  );
}
